### ISSUE TITLE
DC22 - Apps Todo

### ISSUE THREAD

**Issue by coolacid** [mainfram3ca/hackerpyramid#27]
Code Backend Python Console
- [X] Should show all teams and scores on main window
- [X] Needs to send Websocket data to socket server
- [X] Run Round
- [X] Show Runtime
- [ ] Finish up and TODO items

Websocket Server
- [X] Accept connections from console and clients

Audience Client
- [X] Modify code to use Websockets
- [X] Websocket: Timer
- [X] Websocket: Scores
- [X] Websocket: Penny
- [X]  Websocket: Categories
- [X]  Websocket: Video
- [X] Add handlers around video to send states back
- [X] Websocket: Run Round

Android Client
- [X] Modify Code to use websockets
- [X] Websocket: Run Round
- [X] Add presenter mode
- [X] Current Time (Presenter Mode)
- [X] Show Run Time (Presenter Mode)
